export const READ_MEMBERS_REPOSITORY = Symbol("READ_MEMBERS_REPOSITORY");
export const READ_BOOKS_REPOSITORY = Symbol("READ_BOOKS_REPOSITORY");
export const READ_NOMINATIONS_REPOSITORY = Symbol(
  "READ_NOMINATIONS_REPOSITORY",
);
export const READ_SESSIONS_REPOSITORY = Symbol("READ_SESSIONS_REPOSITORY");
export const OPEN_LIBRARY = Symbol("OPEN_LIBRARY");
export const VOTE_PUBLISHER = Symbol("VOTE_PUBLISHER");
